# Generated by Django 4.0.5 on 2022-06-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_order_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_in_rub',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
