# Generated by Django 4.0.5 on 2022-06-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
